# Generated by Django 4.1.3 on 2023-05-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapfiller', 'local_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='english')),
                ('lang_code', models.TextField(default='en')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='mother_language',
            field=models.TextField(default='en'),
        ),
        migrations.AddField(
            model_name='user',
            name='target_language',
            field=models.TextField(default='de'),
        ),
    ]
