# Generated by Django 4.1.3 on 2022-12-17 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gapfiller', 'local_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='choice_selection',
        ),
        migrations.AddField(
            model_name='token',
            name='local_choice_selection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token', to='gapfiller.localchoiceselection'),
        ),
    ]
