# Generated by Django 4.1.3 on 2022-11-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapfiller', 'local_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentrychoiceselconfig',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
