# Generated by Django 4.1.3 on 2022-12-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gapfiller', '0002_userentrygapfillerstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='translation',
            field=models.TextField(default=''),
        ),
    ]
