# Generated by Django 4.1.3 on 2023-01-16 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='name',
            field=models.TextField(default='not name', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='storys', to=settings.AUTH_USER_MODEL),
        ),
    ]
