# Generated by Django 4.1.3 on 2023-01-17 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_alter_story_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='description',
        ),
        migrations.AddField(
            model_name='actor',
            name='scence',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='story.scene'),
        ),
        migrations.AddField(
            model_name='scene',
            name='background',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='scene',
            name='story',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='story.story'),
        ),
    ]
