# Generated by Django 4.1.3 on 2023-01-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_remove_scene_description_actor_scence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='background',
            field=models.ImageField(blank=True, default=None, upload_to='images'),
        ),
    ]
