# Generated by Django 4.1.3 on 2023-01-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_actor_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='scence',
            new_name='scene',
        ),
    ]
