# Generated by Django 4.1.3 on 2023-01-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_rename_scence_actor_scene'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='left',
            field=models.TextField(default='0px'),
        ),
        migrations.AddField(
            model_name='actor',
            name='scale',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='actor',
            name='top',
            field=models.TextField(default='0px'),
        ),
    ]
