# Generated by Django 4.1.3 on 2023-01-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_actor_left_actor_scale_actor_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='scale',
            field=models.TextField(default='scale(1)'),
        ),
    ]
