# Generated by Django 4.1.3 on 2023-01-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0010_alter_dialog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
