# Generated by Django 4.1.3 on 2023-02-12 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0011_scene_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='translation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='option',
            name='translation',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='OptionTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='story.option')),
            ],
        ),
        migrations.CreateModel(
            name='DialogTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='story.dialog')),
            ],
        ),
    ]
