# Generated by Django 4.1.3 on 2023-02-21 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0013_knowledge_alter_actor_left_alter_actor_top_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optiontokens',
            name='aquired',
        ),
        migrations.AddField(
            model_name='optiontokens',
            name='acquired',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acquire_options', to='story.knowledge'),
        ),
    ]
