# Generated by Django 4.1.3 on 2023-02-26 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0014_remove_optiontokens_aquired_optiontokens_acquired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optiontokens',
            name='acquired',
        ),
        migrations.RemoveField(
            model_name='optiontokens',
            name='disabled_k_items',
        ),
        migrations.RemoveField(
            model_name='optiontokens',
            name='required_k_items',
        ),
        migrations.AddField(
            model_name='option',
            name='acquired',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acquire_options', to='story.knowledge'),
        ),
        migrations.AddField(
            model_name='option',
            name='disabled_k_items',
            field=models.ManyToManyField(related_name='disabled_options', to='story.knowledge'),
        ),
        migrations.AddField(
            model_name='option',
            name='required_k_items',
            field=models.ManyToManyField(related_name='require_options', to='story.knowledge'),
        ),
    ]
