# Generated by Django 4.1.3 on 2023-02-26 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0015_remove_optiontokens_acquired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_items', to='story.story'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='users',
            field=models.ManyToManyField(related_name='knowledge_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
