# Generated by Django 4.1.3 on 2023-03-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0016_knowledge_story_knowledge_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='disabled_k_items',
            field=models.ManyToManyField(blank=True, related_name='disabled_options', to='story.knowledge'),
        ),
        migrations.AlterField(
            model_name='option',
            name='required_k_items',
            field=models.ManyToManyField(blank=True, related_name='require_options', to='story.knowledge'),
        ),
    ]
