# Generated by Django 4.1.3 on 2023-03-13 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0017_alter_option_disabled_k_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='top',
            field=models.TextField(default='10px'),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='knowledge_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
