# Generated by Django 4.1.3 on 2023-03-21 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0019_knowledge_deactivated_scenes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collectible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.ImageField(blank=True, default=None, upload_to='images')),
                ('scale', models.TextField(default='scale(1)')),
                ('top', models.TextField(default='10px')),
                ('left', models.TextField(default='50px')),
                ('knowledge_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectible', to='story.knowledge')),
                ('scene', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='collectibles', to='story.scene')),
            ],
        ),
    ]
