# Generated by Django 4.1.3 on 2023-03-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0020_collectible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectible',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
