# Generated by Django 4.1.3 on 2023-04-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0021_alter_collectible_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='podcasts/'),
        ),
        migrations.AddField(
            model_name='option',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='podcasts/'),
        ),
    ]
