# Generated by Django 4.1.3 on 2023-04-21 09:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0022_dialog_audio_option_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='scences', to=settings.AUTH_USER_MODEL),
        ),
    ]
