# Generated by Django 4.1.3 on 2023-04-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0023_scene_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
