# Generated by Django 4.1.3 on 2023-04-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0024_story_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='created',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
