# Generated by Django 4.1.3 on 2023-05-01 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gapfiller', '0001_language_user_mother_language_user_target_language'),
        ('story', '0025_story_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='dest_lang',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dest_lang', to='gapfiller.language'),
        ),
        migrations.AddField(
            model_name='story',
            name='org_lang',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_lang', to='gapfiller.language'),
        ),
    ]
